### PR TITLE
Liberalized press rights

### PR DESCRIPTION
**Pull request by Outta-my-way-burrocrat**
Most dictatorships have total control of the press. Renamed publishing_rights reforms.

### CODE REVIEW

**Comment by Outta-my-way-burrocrat** [comment]
@ccfox when will you be back?

**Comment by ccfox** [comment]
I don't really have a date - I have been busy.

Do you have any other means of contact beyond github? This doesn't allow private messages.

**Comment by Outta-my-way-burrocrat** [comment]
@ccfox If you ever used a public email on this repo I could email you there.

**Comment by Outta-my-way-burrocrat** [comment]
@ccfox zzzzz_snorthiccupcough@protonmail.com

**Comment by ccfox** [comment]
I don't, also had some trouble irl and might be a bit sparse with updates for a while.

**Comment by Outta-my-way-burrocrat** [comment]
@ccfox what needs to be changed?

**Pull request closed without merging**
