### PR TITLE
Liberalized press rights 2nd attempt

### PR DESCRIPTION
**Pull request by Outta-my-way-burrocrat**
Most dictatorships have total control of the press. Renamed publishing_rights reforms. https://github.com/ccfox/CWE-FoxFork/pull/102

Next step: https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/pull/1113

### CODE REVIEW

**Comment by ccfox** [comment]
If its just the name, would it be possible to just change the loc?

**Comment by Outta-my-way-burrocrat** [comment]
No, because a lot of countries have censored_publishing as their publishing rights, and this change will give them Censored Publishing instead of State Publishing.

**Comment by Outta-my-way-burrocrat** [comment]
The alternatives would be to go through the mod and change a lot of countries to firewall_publishing or more, or keep the old buggy code and use the startup decisions to fix the problem; this is a cleaner and smaller fix.

**Comment by ccfox** [comment]
A few of the files are ones I have edited locally, so it might have to wait.

**Comment by Outta-my-way-burrocrat** [comment]
Send me the files and I'll fix them up.

**Comment by ccfox** [comment]
If you had a place for me to send private messages, I could.

**Pull request closed without merging**
