### PR TITLE
Fixed line endings

### PR DESCRIPTION
**Pull request by Outta-my-way-burrocrat**
I HATE line ending bugs

### CODE REVIEW

**Comment by ccfox** [comment]
What are the changes? For me it just shows the whole file as being replaced, but the file is replaced with an exact copy of the file.

**Comment by Outta-my-way-burrocrat** [comment]
GitHub displays line ending changes that way. The only changes should be converting LF (\n) line endings to CRLF (\r\n). GitHub saved a few files using LF instead of CRLF when this repository was added. Most files in Victoria 2 use CRLF line endings.

**Comment by ccfox** [comment]
I don't know what that means, but I have edited a few of these files - I'll push up those changes.

**Comment by Outta-my-way-burrocrat** [comment]
Merge conflicts fixed.

>I don't know what that means, but I have edited a few of these files - I'll push up those changes.

https://en.wikipedia.org/wiki/Newline#Issues_with_different_newline_formats

**Pull request merged**
