### PR TITLE
commonwealthoption3 communist_social check from DoktorKure

### PR DESCRIPTION
**Pull request by Outta-my-way-burrocrat**
https://github.com/ccfox/CWE-FoxFork/pull/23

### CODE REVIEW

**Comment by ccfox** [comment]
I already had this change made locally. Also please stop importing fixes from them.

**Comment by Outta-my-way-burrocrat** [comment]
Ok. I've tried to only pull in bugfixes from their fork. I can guess why they aren't welcome.

**Comment by Outta-my-way-burrocrat** [comment]
@ccfox If any of my PRs cause controversy in the forums, could you relay the complaints to me?

**Comment by ccfox** [comment]
Do you have any place you have an account that allows any degree of privacy in conversation at all?

**Comment by Outta-my-way-burrocrat** [comment]
@ccfox I have a very boring public email address and my personal anti-harm ethic allows me some private space. zzzzz_snorthiccupcough@protonmail.com

**Pull request closed without merging**
