### PR TITLE
Tweaked discoveries and research_and_development techs

### PR DESCRIPTION
**Pull request by Outta-my-way-burrocrat**
Restored branch of https://github.com/ccfox/CWE-FoxFork/pull/14

### CODE REVIEW

**Comment by ccfox** [comment]
These are fixes related to the tech changes, right?

**Comment by Outta-my-way-burrocrat** [comment]
Hi.

It replaces Cable Television Networks with a tweaked Information theory tech from CWE and tweaks the other techs to fit.

**Comment by ccfox** [comment]
Is it tested?

**Comment by Outta-my-way-burrocrat** [comment]
I have not tested this branch yet.

**Comment by Outta-my-way-burrocrat** [comment]
This seems to work.

**Comment by ccfox** [comment]
Alright. I have a few things I want to put forward, and then I'll merge.

**Comment by Outta-my-way-burrocrat** [comment]
>Alright. I have a few things I want to put forward, and then I'll merge.

What's up next?

**Comment by ccfox** [comment]
> > Alright. I have a few things I want to put forward, and then I'll merge.
> 
> What's up next?

I'm trying to fix a few of the election events, and removing some anachronistic events that don't make any sense and just clutter up the already cluttered 'misc' events.

**Comment by Outta-my-way-burrocrat** [comment]
The current branch: Cable Television Networks has been replaced with Early Programming Language; Information Theory and its inventions was moved to tier 2 research_and_development.

**Comment by Outta-my-way-burrocrat** [comment]
@ccfox should I close this?

**Comment by ccfox** [comment]
I'm still not actually sure what the goal of these changes are, can you explain them?

**Pull request closed without merging**
